declare const styles: {
    readonly constants: string;
    readonly primaryLightest: string;
    readonly offWhite: string;
    readonly tertiaryLight: string;
    readonly boldBorderWidth: string;
    readonly card: string;
    readonly activeCard: string;
    readonly cardInterior: string;
    readonly name: string;
    readonly cardElement: string;
    readonly numberField: string;
    readonly initiative: string;
    readonly health: string;
    readonly armorClass: string;
    readonly notes: string;
    readonly buttons: string;
    readonly close: string;
    readonly notesBtn: string;
};
export = styles;
